### ISSUE TITLE
CV Review

### ISSUE THREAD

**Issue by AbdelhamidGamal** [amrsekilly/amr-elsekilly-resume-template#10]
[deleted]

**Comment by 3b7ameed** [comment]
Hey Amr, 

I updated my resume as someone in an interview last week advised me to put the projects I worked in on every company so here's the updated version 

https://docs.google.com/document/d/1ugf_joUTPudWXaIwh1Y7wfXt9R78y-83rHEDy5QYzTI/edit?usp=sharing
