### ISSUE TITLE
CV Review 

### ISSUE THREAD

**Issue by abanoub-asaad** [amrsekilly/amr-elsekilly-resume-template#6]
I've sent to you my resume in mail
**Also, I've replied to the mail with a link to Google Docs with commenting access.**

Thank you in advance.

**Comment by amrsekilly** [comment]
Done, I've reviewed it on Google docs @Abanoub-Asaad. Keep up the good work 🔥 

I'll keep the issue open, in case you have any questions or need any other feedback. And feel free to close it once you reach the desired results.

**Comment by abanoub-asaad** [comment]
Thank you so much for your feedback
I really appreciate your efforts and time.

**Comment by amrsekilly** [comment]
You're welcome, Abanoub!
